GET  http://127.0.0.1:8000/api/products HTTP/1.1

###

PUT  http://127.0.0.1:8000/api/products/6 HTTP/1.1
content-type: application/json

{
    "title": "New new new new"
    
}

###

DELETE   http://127.0.0.1:8000/api/products/5 HTTP/1.1

###

DELETE   http://127.0.0.1:8000/api/users/1 HTTP/1.1

###

GET  http://127.0.0.1:8000/api/users HTTP/1.1

###

